/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Parametros {
	float a;
	float b;
	char operator;
};
typedef struct Parametros Parametros;

#define cal 1
#define calc_ver 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  int * suma_1(struct Parametros *, CLIENT *);
extern  int * suma_1_svc(struct Parametros *, struct svc_req *);
#define resta 2
extern  int * resta_1(struct Parametros *, CLIENT *);
extern  int * resta_1_svc(struct Parametros *, struct svc_req *);
#define mult 3
extern  int * mult_1(struct Parametros *, CLIENT *);
extern  int * mult_1_svc(struct Parametros *, struct svc_req *);
#define div 4
extern  float * div_1(struct Parametros *, CLIENT *);
extern  float * div_1_svc(struct Parametros *, struct svc_req *);
extern int cal_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define resta 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define mult 3
extern  int * mult_1();
extern  int * mult_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
extern int cal_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Parametros (XDR *, Parametros*);

#else /* K&R C */
extern bool_t xdr_Parametros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
